config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews

  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country, :presence => true
  validates :inventory, :presence => true

  scope :recent_products, -> { order(created_at: :desc).limit(3)}

  scope :most_reviews, -> {(
    select("products.name, products.cost, products.country, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(3)
    )}

    scope :made_in_hyrule, -> { where(country: "Hyrule Castle")}
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :author, :presence => true
  validates :content, :presence => true
  validates :rating, :presence => true
  validates :rating, :inclusion => 1..5
  validates :content, length: { in: 50..250 }

  def char_count
    if self.content.size  >= 50 && self.content.size <= 250
      return self.content
    else
      return "invalid review"
    end
  end

  def rating_check
    if self.rating >0 && self.rating <= 5
      return self.rating
    else
      return "invalid  rating"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    render :index
  end
  def new
   @product = Product.new
 end
 def create
   @product = Product.new(product_params)
   flash[:notice] = "#{@product.name} was added to the list!"
   if @product.save
     redirect_to  products_path
   else
     render :new
   end
 end
 def edit
   @product= Product.find(params[:id])
   render :edit
 end
 def update
   @product= Product.find(params[:id])
   if @product.update(product_params)
     flash[:notice] = "#{@product.name} was updated!"
     redirect_to products_path
   else
     render :edit
     end
   end
 def destroy
   @product = Product.find(params[:id])
   @product.destroy
    flash[:notice] = "#{@product.name} was deleted."
   redirect_to products_path
 end
 def show
   @product = Product.find(params[:id])
   render :show
 end
 private
 def product_params
   params.require(:product).permit(:name, :cost, :country, :inventory)
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(reviews_params)
    if @review.save
      flash[:notice] = "#{@review.author}, thank you for your review!"
      redirect_to product_path(@review.product_id)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(reviews_params)
      redirect_to product_path(@review.product_id)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
    def reviews_params
      params.require(:review).permit(:author, :content, :rating)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @products = Product.all
    @reviews= Review.all

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerudo Valley</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class="container">
      <h2 id="flash-notice"><%= flash[:notice] %></h2>
    </div>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render('layouts/errors', :object => @product) %>

<%= form_for [@product] do |f| %>
  <p><%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.label :inventory %>
  <%= f.text_field :inventory %>
<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<div class="container jumbotron" id="edit">
  <h2>Edit This Product </h2>

  <%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="container" id="products">
  <h2> <%= link_to "Back", root_path%></h2>
  <div class="jumbotron" id="productjumbo">
    <h1>Products</h1>
    <p><%= link_to "Add a New Product", new_product_path(@product) %></p>
  </div>
  <% @products.each do |product| %>
  <h3><%= link_to product.name, product_path(product)%> - $<%=product.cost%></h3>
  <h5>(Made in <%=product.country%>)</h5>
  <h5>Stock: <%=product.inventory%></h5>
  <hr>
  <% end %>
</div>
</div>

app/views/products/new.html.erb
<div class="container jumbotron" id="show">
  <h1>New Product</h1>
  <%= render "products/form" %>

  <% if @product.errors.any? %>
    <h3>Oops there were some errors. Please try again:</h3>
    <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<div>

app/views/products/show.html.erb
<div class="container jumbotron" id="show">
  <h2><%= @product.name %></h2>
  <h3>Cost: $<%= @product.cost %></h3>
  <h3>Made in <%= @product.country %></h3>
  <p><%= link_to "Edit", edit_product_path(@product) %> |
<%= link_to "Delete Product", product_path(@product),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>

   <% if @product.reviews.any? %>
   <h4>Here are the reviews for this product:</h4>

   <ul>
     <% @product.reviews.each do |review| %>
       <p>
         By: <%= review.author %> | Rating: <%= review.rating_check %> <br>
         <%= review.char_count %>
       </p>
     <% end %>
   </ul>
 <% else %>
   <p>There are no reviews yet!</p>
 <% end %>
 <p><%= link_to "Add a review", new_product_review_path(@product) %></p>
 <p><%= link_to "Delete product", product_path(@product),
                         :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>

 <p><%= link_to "Return to products", products_path %></p>
</div>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :rating%>
  <%= f.text_field :rating%>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<div class="container jumbotron" id="show">

  <h1>New review for <%= @product.name %></h1>

  <%= render 'form' %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <h2 id="gerudo">Gerudo Valley General Store</h2>
</div>
  <div class="row">
    <div class="col-md-6">
      <div class="jumbotron" id="title">
        <button class="btn btn-danger" id="button"><%= link_to "PRODUCTS", products_path(@products) %></button>
        <br>
        <p>Your one stop shop for everything you'll ever need in Hyrule!</p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="new_product">
        <h1>New Products:</h1>
        <% @products.recent_products.each do |product| %>
        <h3><%= link_to product.name, product_path(product)%></h3>
        <h5>Launch Date: <%= product.created_at.strftime("%Y-%m-%d") %></h5>
        <% end %>
        <br><br>
        <h1>Most Reviewed:</h1>
        <% @products.most_reviews.each do |product| %>
        <h3><%= product.name %></h3>
        <h5><%= product.reviews_count %> Reviews</h5>
        <% end %>
        <br><br>
        <h1>Made in Hyrule: </h1>
        <% @products.made_in_hyrule.each do |product| %>
        <h3><%= product.name %></h3>
        <h5>Stock: <%= product.inventory %> </h5>
        <% end %>
      </div>
    </div>
  </div>